site_name: CharmsBot

nav:
  - Home: index.md
  - Commands: commands.md
  - Changelog: changelog.md
  - Contact: contact.md
  - Legal: legal.md
  - Terms of Service: terms.md
  - Privacy Policy: privacy.md
